// Mock data for development - will be replaced with Sanity data

export const mockTestimonials = [
  {
    _id: '1',
    title: 'Transformed our digital infrastructure',
    quote: 'Ignis AI Labs has completely transformed our digital infrastructure with their technical expertise and innovative solutions. Our operations are now more efficient than ever.',
    author: 'Sarah Johnson',
    role: 'CEO',
    company: 'Indocool',
    companyLogo: '/images/testimonials/Indocool.png',
    companyLogoColor: '#a855f7',
    order: 1,
  },
  {
    _id: '2',
    title: 'Game-changer',
    quote: 'Working with Ignis AI Labs has been a game-changer. Their software solutions are robust, scalable, and always delivered on time. Highly professional team.',
    author: 'Mark Thompson',
    role: 'Director',
    company: 'Muphile Labs',
    companyLogo: '/images/testimonials/muphileLabs.jpg',
    companyLogoColor: '#6366f1',
    order: 2,
  },
  {
    _id: '3',
    title: 'Elevated our tech stack',
    quote: 'Ignis AI Labs has helped us modernize our technology stack and streamline our operations. Their engineering excellence is unmatched. Highly recommend!',
    author: 'Jessica Moore',
    role: 'CEO',
    company: 'Narayna Pearls',
    companyLogo: '/images/testimonials/NaraynaPearls.png',
    companyLogoColor: '#7c3aed',
    order: 3,
  },
  {
    _id: '4',
    title: 'Responsive and professional',
    quote: 'Working with Ignis AI Labs is a pleasure. Responsive, professional, and deliver exceptional software solutions that exceed expectations.',
    author: 'Matthew Taylor',
    role: 'Director',
    company: 'Waioz',
    companyLogo: '/images/testimonials/Waioz.png',
    companyLogoColor: '#8b5cf6',
    order: 4,
  },
  
];

export const mockStats = {
  happyCustomers: '10+',
  projectsCompleted: '50+',
  satisfaction: '99.8%',
};

export const mockProcessSteps = [
  {
    _id: '1',
    title: 'Discovery',
    subtitle: 'Problem definition & data mapping',
    description: 'We analyze your business requirements, map data sources, and define clear objectives for your project.',
    icon: 'search',
    order: 1,
  },
  {
    _id: '2',
    title: 'Architecture',
    subtitle: 'Blueprints, security, data contracts',
    description: 'Design robust system architecture with security protocols, scalable blueprints, and clear data contracts.',
    icon: 'layout',
    order: 2,
  },
  {
    _id: '3',
    title: 'Development',
    subtitle: 'CI/CD, modular build',
    description: 'Build with modern DevOps practices, automated pipelines, and modular components for flexibility.',
    icon: 'code',
    order: 3,
  },
  {
    _id: '4',
    title: 'Validation',
    subtitle: 'Integration & performance checks',
    description: 'Rigorous testing of integrations, performance benchmarks, and quality assurance protocols.',
    icon: 'check-circle',
    order: 4,
  },
  {
    _id: '5',
    title: 'Deployment',
    subtitle: 'Cloud delivery & monitoring',
    description: 'Seamless cloud deployment with continuous monitoring, logging, and real-time health checks.',
    icon: 'upload-cloud',
    order: 5,
  },
  {
    _id: '6',
    title: 'Scaling',
    subtitle: 'Cost-performance optimization',
    description: 'Optimize resources, enhance performance, and ensure cost-effective scaling as you grow.',
    icon: 'trending-up',
    order: 6,
  },
];

export const mockFeaturedTestimonial = {
  author: 'Barry Allen',
  role: 'CEO of Speed4s',
  title: 'Lightning-fast',
  quote: "Ignis AI Labs is a lifesaver! Their lightning-fast development cycles keep up with my company's needs. It's like having my own elite engineering team on standby. Thanks, Ignis AI Labs!",
};

export const mockBenefits = [
  {
    _id: '1',
    title: 'Expert Team',
    description: 'Skilled engineers and consultants with deep expertise across technologies.',
    icon: 'users',
    order: 1,
  },
  {
    _id: '2',
    title: 'Rapid Delivery',
    description: 'Agile methodology ensures fast iterations and timely project completion.',
    icon: 'zap',
    order: 2,
  },
  {
    _id: '3',
    title: 'Scalable Solutions',
    description: 'Architecture designed to grow with your business needs.',
    icon: 'trending-up',
    order: 3,
  },
  {
    _id: '4',
    title: 'Modern Tech Stack',
    description: 'Latest technologies and best practices for future-proof solutions.',
    icon: 'code',
    order: 4,
  },
  {
    _id: '5',
    title: 'End-to-End Delivery',
    description: 'From discovery to deployment and beyond, we handle the entire lifecycle.',
    icon: 'layers',
    order: 5,
  },
  {
    _id: '6',
    title: 'Quality Assurance',
    description: 'Rigorous testing and validation to ensure robust, reliable systems.',
    icon: 'shield-check',
    order: 6,
  },
];

export const mockServices = [
  {
    _id: '1',
    title: 'Software Engineering',
    description: 'Custom platforms, cloud-native systems, resilient delivery.',
    icon: 'cpu',
    order: 1,
  },
  {
    _id: '2',
    title: 'AI & ML Engineering',
    description: 'Production-grade models, pipelines, model ops.',
    icon: 'brain',
    order: 2,
  },
  {
    _id: '3',
    title: 'Business & Financial Analysis',
    description: 'Forecasting, scenario modelling, decision systems.',
    icon: 'trending-up',
    order: 3,
  },
  {
    _id: '4',
    title: 'UX & Product Design',
    description: 'Minimal product systems, rapid prototyping.',
    icon: 'pen-tool',
    order: 4,
  },
  {
    _id: '5',
    title: 'Third-Party Integrations',
    description: 'SAP, ERP, CRM, logistics and communication connectors.',
    icon: 'plug',
    order: 5,
  },
  {
    _id: '6',
    title: 'Power BI & Analytics',
    description: 'Operational dashboards and governance.',
    icon: 'bar-chart',
    order: 6,
  },
];

export const mockProjects = [
  {
    _id: '1',
    title: 'Supplier Portal',
    description: 'Streamlined vendor management with automated onboarding, quote requests, performance tracking.',
    category: 'Enterprise Software',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    techStack: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    metrics: { label: '60% faster onboarding', icon: 'zap' },
    gradient: 'from-purple-500 to-indigo-500',
    gridSize: 'wide',
    order: 1,
  },
  {
    _id: '2',
    title: 'Customer Portal',
    description: 'Self-service customer interface for orders, invoicing, support tickets, and account management.',
    category: 'Customer Experience',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    techStack: ['Vue.js', 'Express', 'MongoDB', 'Azure'],
    metrics: { label: '85% support ticket reduction', icon: 'trending-down' },
    gradient: 'from-blue-500 to-cyan-500',
    gridSize: 'regular',
    order: 2,
  },
  {
    _id: '3',
    title: 'PRC Template Creator',
    description: 'Dynamic document generation engine for purchase requisitions with approval workflows and templates.',
    category: 'Automation',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    techStack: ['Angular', 'Python', 'Redis', 'Docker'],
    metrics: { label: '70% faster document generation', icon: 'file-text' },
    gradient: 'from-green-500 to-emerald-600',
    gridSize: 'tall',
    order: 3,
  },
  {
    _id: '4',
    title: 'Warehouse Management System',
    description: 'Real-time inventory tracking, picking optimization, and fulfillment automation for distribution centers.',
    category: 'Supply Chain',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
    techStack: ['React Native', 'Java', 'Oracle', 'Kubernetes'],
    metrics: { label: '45% picking efficiency increase', icon: 'package' },
    gradient: 'from-orange-500 to-orange-600',
    gridSize: 'regular',
    order: 4,
  },
  {
    _id: '5',
    title: 'Import/Export Workflow',
    description: 'End-to-end logistics management for international shipments with customs documentation and compliance.',
    category: 'Logistics',
    image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&q=80',
    techStack: ['Next.js', 'Go', 'MySQL', 'GCP'],
    metrics: { label: '90% customs compliance', icon: 'globe' },
    gradient: 'from-teal-500 to-teal-600',
    gridSize: 'wide',
    order: 5,
  },
  {
    _id: '6',
    title: 'Procure-to-Pay',
    description: 'Integrated procurement platform connecting requisitions, approvals, purchasing, and payment processing.',
    category: 'Financial Systems',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    techStack: ['React', 'SAP', 'PostgreSQL', 'Microservices'],
    metrics: { label: '50% faster payment cycles', icon: 'credit-card' },
    gradient: 'from-pink-500 to-fuchsia-500',
    gridSize: 'regular',
    order: 6,
  },
];

export const mockFAQs = [
  {
    _id: '1',
    question: 'What types of software projects do you handle?',
    answer: 'We handle a wide range of software development projects including custom web applications, enterprise software systems, AI/ML solutions, cloud-native platforms, API integrations, mobile applications, and data analytics systems. Our team specializes in full-stack development and end-to-end solutions.',
    order: 1,
  },
  {
    _id: '2',
    question: 'What is the typical project timeline?',
    answer: 'Project timelines vary based on complexity and scope. Small projects typically take 2-4 weeks, medium projects 1-3 months, and large enterprise solutions 3-6 months. We provide detailed timelines during the discovery phase and maintain transparent communication throughout the development process.',
    order: 2,
  },
  {
    _id: '3',
    question: 'Can you work with our existing systems?',
    answer: "Absolutely! We specialize in integrating with existing systems and infrastructure. We'll analyze your current tech stack, identify integration points, and ensure seamless connectivity with your existing tools, databases, and third-party services.",
    order: 3,
  },
  {
    _id: '4',
    question: 'What technologies and frameworks do you use?',
    answer: 'We work with modern tech stacks including React, Vue.js, Angular, Node.js, Python, Java, Go, and cloud platforms like AWS, Azure, and GCP. We also specialize in AI/ML frameworks, microservices architecture, and DevOps tools. We choose technologies based on your specific requirements and long-term goals.',
    order: 4,
  },
  {
    _id: '5',
    question: 'Do you provide ongoing support and maintenance?',
    answer: "Yes, we offer comprehensive support and maintenance packages. This includes bug fixes, security updates, performance optimization, feature enhancements, and 24/7 monitoring. We ensure your software remains secure, performant, and up-to-date with the latest technologies.",
    order: 5,
  },
  {
    _id: '6',
    question: 'How can I contact your team?',
    answer: 'You can reach our team through multiple channels: email at support@ignisailabs.com, through our contact form, or by booking a consultation call. We typically respond within 24 hours and are available for urgent matters.',
    order: 6,
  },
];

export const mockTrustedByLogos = [
  { name: 'TechCorp', logo: '' },
  { name: 'InnovateLab', logo: '' },
  { name: 'DevSolutions', logo: '' },
  { name: 'CodeStudio', logo: '' },
  { name: 'DigitalFirst', logo: '' },
];
