// Mock data for development - will be replaced with Sanity data

export const mockTestimonials = [
  {
    _id: '1',
    title: 'Transformed our design process',
    quote: 'Ignis AI Labs has completely transformed our design process with their creativity and attention to detail.',
    author: 'Sarah Johnson',
    role: 'CEO',
    company: 'Indocool',
    companyLogo: '/images/testimonials/Indocool.png',
    companyLogoColor: '#a855f7',
    order: 1,
  },
  {
    _id: '2',
    title: 'Game-changer',
    quote: 'Working with Ignis AI Labs has been a game-changer. Designs are top-notch and always delivered on time.',
    author: 'Mark Thompson',
    role: 'Director',
    company: 'Muphile Labs',
    companyLogo: '/images/testimonials/muphileLabs.jpg',
    companyLogoColor: '#6366f1',
    order: 2,
  },
  {
    _id: '3',
    title: 'Elevated our visual identity',
    quote: 'Ignis AI Labs has helped us elevate our visual identity and stand out in a crowded market. Highly recommend!',
    author: 'Jessica Moore',
    role: 'CEO',
    company: 'Narayna Pearls',
    companyLogo: '/images/testimonials/NaraynaPearls.png',
    companyLogoColor: '#7c3aed',
    order: 3,
  },
  {
    _id: '4',
    title: 'Responsive and professional',
    quote: 'Working with Ignis AI Labs is a pleasure. Responsive, professional, and deliver exceptional designs.',
    author: 'Matthew Taylor',
    role: 'Director',
    company: 'Waioz',
    companyLogo: '/images/testimonials/Waioz.png',
    companyLogoColor: '#8b5cf6',
    order: 4,
  },
  
];

export const mockStats = {
  happyCustomers: '10+',
  projectsCompleted: '50+',
  satisfaction: '99.8%',
};

export const mockProcessSteps = [
  {
    _id: '1',
    title: 'Discovery',
    subtitle: 'Problem definition & data mapping',
    description: 'We analyze your business requirements, map data sources, and define clear objectives for your project.',
    icon: 'search',
    order: 1,
  },
  {
    _id: '2',
    title: 'Architecture',
    subtitle: 'Blueprints, security, data contracts',
    description: 'Design robust system architecture with security protocols, scalable blueprints, and clear data contracts.',
    icon: 'layout',
    order: 2,
  },
  {
    _id: '3',
    title: 'Development',
    subtitle: 'CI/CD, modular build',
    description: 'Build with modern DevOps practices, automated pipelines, and modular components for flexibility.',
    icon: 'code',
    order: 3,
  },
  {
    _id: '4',
    title: 'Validation',
    subtitle: 'Integration & performance checks',
    description: 'Rigorous testing of integrations, performance benchmarks, and quality assurance protocols.',
    icon: 'check-circle',
    order: 4,
  },
  {
    _id: '5',
    title: 'Deployment',
    subtitle: 'Cloud delivery & monitoring',
    description: 'Seamless cloud deployment with continuous monitoring, logging, and real-time health checks.',
    icon: 'upload-cloud',
    order: 5,
  },
  {
    _id: '6',
    title: 'Scaling',
    subtitle: 'Cost-performance optimization',
    description: 'Optimize resources, enhance performance, and ensure cost-effective scaling as you grow.',
    icon: 'trending-up',
    order: 6,
  },
];

export const mockFeaturedTestimonial = {
  author: 'Barry Allen',
  role: 'CEO of Speed4s',
  title: 'Lightning-fast',
  quote: "Ignis AI Labs is a lifesaver! Their lightning-fast design service keeps up with my company's needs. It's like having my own design team on standby. Thanks, Ignis AI Labs!",
};

export const mockBenefits = [
  {
    _id: '1',
    title: 'Expert Team',
    description: 'Skilled engineers and consultants with deep expertise across technologies.',
    icon: 'users',
    order: 1,
  },
  {
    _id: '2',
    title: 'Rapid Delivery',
    description: 'Agile methodology ensures fast iterations and timely project completion.',
    icon: 'zap',
    order: 2,
  },
  {
    _id: '3',
    title: 'Scalable Solutions',
    description: 'Architecture designed to grow with your business needs.',
    icon: 'trending-up',
    order: 3,
  },
  {
    _id: '4',
    title: 'Modern Tech Stack',
    description: 'Latest technologies and best practices for future-proof solutions.',
    icon: 'code',
    order: 4,
  },
  {
    _id: '5',
    title: 'End-to-End Delivery',
    description: 'From discovery to deployment and beyond, we handle the entire lifecycle.',
    icon: 'layers',
    order: 5,
  },
  {
    _id: '6',
    title: 'Quality Assurance',
    description: 'Rigorous testing and validation to ensure robust, reliable systems.',
    icon: 'shield-check',
    order: 6,
  },
];

export const mockServices = [
  {
    _id: '1',
    title: 'Software Engineering',
    description: 'Custom platforms, cloud-native systems, resilient delivery.',
    icon: 'cpu',
    order: 1,
  },
  {
    _id: '2',
    title: 'AI & ML Engineering',
    description: 'Production-grade models, pipelines, model ops.',
    icon: 'brain',
    order: 2,
  },
  {
    _id: '3',
    title: 'Business & Financial Analysis',
    description: 'Forecasting, scenario modelling, decision systems.',
    icon: 'trending-up',
    order: 3,
  },
  {
    _id: '4',
    title: 'UX & Product Design',
    description: 'Minimal product systems, rapid prototyping.',
    icon: 'pen-tool',
    order: 4,
  },
  {
    _id: '5',
    title: 'Third-Party Integrations',
    description: 'SAP, ERP, CRM, logistics and communication connectors.',
    icon: 'plug',
    order: 5,
  },
  {
    _id: '6',
    title: 'Power BI & Analytics',
    description: 'Operational dashboards and governance.',
    icon: 'bar-chart',
    order: 6,
  },
];

export const mockProjects = [
  {
    _id: '1',
    title: 'Supplier Portal',
    description: 'Streamlined vendor management with automated onboarding, quote requests, performance tracking.',
    category: 'Enterprise Software',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    techStack: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    metrics: { label: '60% faster onboarding', icon: 'zap' },
    gradient: 'from-purple-500 to-indigo-500',
    gridSize: 'wide',
    order: 1,
  },
  {
    _id: '2',
    title: 'Customer Portal',
    description: 'Self-service customer interface for orders, invoicing, support tickets, and account management.',
    category: 'Customer Experience',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    techStack: ['Vue.js', 'Express', 'MongoDB', 'Azure'],
    metrics: { label: '85% support ticket reduction', icon: 'trending-down' },
    gradient: 'from-blue-500 to-cyan-500',
    gridSize: 'regular',
    order: 2,
  },
  {
    _id: '3',
    title: 'PRC Template Creator',
    description: 'Dynamic document generation engine for purchase requisitions with approval workflows and templates.',
    category: 'Automation',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    techStack: ['Angular', 'Python', 'Redis', 'Docker'],
    metrics: { label: '70% faster document generation', icon: 'file-text' },
    gradient: 'from-green-500 to-emerald-600',
    gridSize: 'tall',
    order: 3,
  },
  {
    _id: '4',
    title: 'Warehouse Management System',
    description: 'Real-time inventory tracking, picking optimization, and fulfillment automation for distribution centers.',
    category: 'Supply Chain',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
    techStack: ['React Native', 'Java', 'Oracle', 'Kubernetes'],
    metrics: { label: '45% picking efficiency increase', icon: 'package' },
    gradient: 'from-orange-500 to-orange-600',
    gridSize: 'regular',
    order: 4,
  },
  {
    _id: '5',
    title: 'Import/Export Workflow',
    description: 'End-to-end logistics management for international shipments with customs documentation and compliance.',
    category: 'Logistics',
    image: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&q=80',
    techStack: ['Next.js', 'Go', 'MySQL', 'GCP'],
    metrics: { label: '90% customs compliance', icon: 'globe' },
    gradient: 'from-teal-500 to-teal-600',
    gridSize: 'large',
    order: 5,
  },
  {
    _id: '6',
    title: 'Procure-to-Pay',
    description: 'Integrated procurement platform connecting requisitions, approvals, purchasing, and payment processing.',
    category: 'Financial Systems',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    techStack: ['React', 'SAP', 'PostgreSQL', 'Microservices'],
    metrics: { label: '50% faster payment cycles', icon: 'credit-card' },
    gradient: 'from-pink-500 to-fuchsia-500',
    gridSize: 'regular',
    order: 6,
  },
];

export const mockPricing = [
  {
    _id: '1',
    name: 'Standard',
    price: 2995,
    billingPeriod: 'month',
    tagline: 'Perfect for starters and small teams.',
    highlighted: false,
    features: [
      { feature: 'Unlimited requests', included: true },
      { feature: 'One request at a time', included: true },
      { feature: '2-days delivery', included: true },
      { feature: 'Unlimited revisions', included: true },
      { feature: 'Framer development', included: true },
      { feature: 'Weekly calls', included: true },
      { feature: 'Dashboard Access', included: true },
      { feature: 'Unlimited stock photos', included: true },
    ],
    ctaText: 'Get started',
    order: 1,
  },
  {
    _id: '2',
    name: 'Premium',
    price: 5995,
    billingPeriod: 'month',
    tagline: 'Exclusive and advanced features.',
    highlighted: true,
    features: [
      { feature: 'Unlimited requests', included: true },
      { feature: '2 requests at a time', included: true },
      { feature: 'Same day delivery', included: true },
      { feature: 'Unlimited revisions', included: true },
      { feature: 'Framer development', included: true },
      { feature: 'Weekly calls', included: true },
      { feature: 'Dashboard Access', included: true },
      { feature: 'Unlimited stock photos', included: true },
    ],
    ctaText: 'Get started',
    order: 2,
  },
];

export const mockFAQs = [
  {
    _id: '1',
    question: 'How many design requests can I make?',
    answer: 'With your subscription, you have unlimited design requests. You can submit as many design projects as you need, and our team will work on them based on your priority and our workload.',
    order: 1,
  },
  {
    _id: '2',
    question: 'What is the turnaround time for design requests?',
    answer: 'Our standard plan offers 2-day delivery for most design requests. Premium subscribers enjoy same-day delivery for urgent projects. Complex projects may require additional time, which we will communicate upfront.',
    order: 2,
  },
  {
    _id: '3',
    question: 'Can I request revisions to my designs?',
    answer: "Absolutely! We offer unlimited revisions on all plans. We'll continue refining your designs until you're completely satisfied with the final result.",
    order: 3,
  },
  {
    _id: '4',
    question: 'What types of designs do you offer?',
    answer: 'We offer a wide range of design services including website design, logo design, mobile app design, branding, UI/UX design, illustrations, social media graphics, and much more.',
    order: 4,
  },
  {
    _id: '5',
    question: 'Do you offer refunds?',
    answer: "Yes, we offer a money-back guarantee. If you're not satisfied with our service within the first 14 days, we'll provide a full refund, no questions asked.",
    order: 5,
  },
  {
    _id: '6',
    question: 'How can I contact your support team?',
    answer: 'You can reach our support team through multiple channels: email at support@ignisailabs.com, through your dashboard, or by booking a call with our team. We typically respond within 24 hours.',
    order: 6,
  },
];

export const mockTrustedByLogos = [
  { name: 'TechCorp', logo: '' },
  { name: 'InnovateLab', logo: '' },
  { name: 'DesignHub', logo: '' },
  { name: 'CreativeStudio', logo: '' },
  { name: 'DigitalFirst', logo: '' },
];
